version: 0.1 #Ddon't touch 勿動
debug: False
client_id: 720534269927096370
#You need to upload your image(s) here 你必須上傳你的相片到這裡
#https://discordapp.com/developers/applications/<client_id>/rich-presence/assets

large_image: 
  text: 'laptop'
  Enable: False

large_text: 
  text: '  ' #滑鼠游標移動上去時的顯示
  Enable: True

small_image: 
  text: 'laptop'
  Enable: True

small_text: 
  text: '  ' #滑鼠游標移動上去時的顯示
  Enable: True

state: 
  text: 'TaiwanTorchRz'
  Enable: True

details: 
  text: '工作中'
  Enable: True

start:
  int: 0
  Enable: True

end: 
  int: 1
  Enable: True

name: <大標題是DC應用程式名稱> 

