client_id: 720534269927096370
debug: true
details:
  Enable: true
  text: test
end:
  Enable: true
  int: 1
large_image:
  Enable: true
  text: test
large_text:
  Enable: true
  text: test
name: "<\u5927\u6A19\u984C\u662FDC\u61C9\u7528\u7A0B\u5F0F\u540D\u7A31>"
small_image:
  Enable: true
  text: laptop
small_text:
  Enable: false
  text: '0'
start:
  Enable: true
  int: 0
state:
  Enable: true
  text: test
update_timer: 5
